### ISSUE TITLE
Option for Growth Curve Modeling?

### ISSUE THREAD

**Issue by benminder** [semlj/semlj#10]
Very excited to see SEMLj bring Lavaan to Jamovi!

Is it possible to add an option to enable growth curve modelling? There is currently an option to include mean structures, but not to fix manifest intercepts to zero or allow latent intercepts to vary freely. 

[Lavaan](https://www.lavaan.ugent.be/tutorial/growth.html) enables these options by default when using the "growth" command instead of "sem". Maybe a toggle switch could be included to specify whether SEMLj uses the growth or sem command? Alternatively, adding direct options for these parameters would also be really helpful.

**Comment by mcfanda** [comment]
thanks for the suggestion. What do your think are the lavaan options that you cannot toggle in SEMLj? If you list them, we implement them.

**Comment by mcfanda** [comment]
done
